// Generated by gencpp from file hospitalbot/Communication.msg
// DO NOT EDIT!


#ifndef HOSPITALBOT_MESSAGE_COMMUNICATION_H
#define HOSPITALBOT_MESSAGE_COMMUNICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hospitalbot
{
template <class ContainerAllocator>
struct Communication_
{
  typedef Communication_<ContainerAllocator> Type;

  Communication_()
    : source()
    , target()
    , type()
    , metadata()
    , status()  {
    }
  Communication_(const ContainerAllocator& _alloc)
    : source(_alloc)
    , target(_alloc)
    , type(_alloc)
    , metadata(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _source_type;
  _source_type source;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_type;
  _target_type target;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _metadata_type;
  _metadata_type metadata;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::hospitalbot::Communication_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hospitalbot::Communication_<ContainerAllocator> const> ConstPtr;

}; // struct Communication_

typedef ::hospitalbot::Communication_<std::allocator<void> > Communication;

typedef boost::shared_ptr< ::hospitalbot::Communication > CommunicationPtr;
typedef boost::shared_ptr< ::hospitalbot::Communication const> CommunicationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hospitalbot::Communication_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hospitalbot::Communication_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hospitalbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hospitalbot': ['/home/darkboy/catkin_ws/src/hospitalbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::Communication_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::Communication_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::Communication_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::Communication_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hospitalbot::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc0cceee922687683f945debbb6595bd";
  }

  static const char* value(const ::hospitalbot::Communication_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc0cceee92268768ULL;
  static const uint64_t static_value2 = 0x3f945debbb6595bdULL;
};

template<class ContainerAllocator>
struct DataType< ::hospitalbot::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hospitalbot/Communication";
  }

  static const char* value(const ::hospitalbot::Communication_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hospitalbot::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string source\n\
string target\n\
string type\n\
string metadata\n\
string status\n\
";
  }

  static const char* value(const ::hospitalbot::Communication_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hospitalbot::Communication_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.target);
      stream.next(m.type);
      stream.next(m.metadata);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Communication_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hospitalbot::Communication_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hospitalbot::Communication_<ContainerAllocator>& v)
  {
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.source);
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "metadata: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.metadata);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOSPITALBOT_MESSAGE_COMMUNICATION_H
