// Generated by gencpp from file hospitalbot/Motor.msg
// DO NOT EDIT!


#ifndef HOSPITALBOT_MESSAGE_MOTOR_H
#define HOSPITALBOT_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hospitalbot
{
template <class ContainerAllocator>
struct Motor_
{
  typedef Motor_<ContainerAllocator> Type;

  Motor_()
    : left_velocity(0.0)
    , right_velocity(0.0)
    , time(0)  {
    }
  Motor_(const ContainerAllocator& _alloc)
    : left_velocity(0.0)
    , right_velocity(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef double _left_velocity_type;
  _left_velocity_type left_velocity;

   typedef double _right_velocity_type;
  _right_velocity_type right_velocity;

   typedef uint64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::hospitalbot::Motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hospitalbot::Motor_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_

typedef ::hospitalbot::Motor_<std::allocator<void> > Motor;

typedef boost::shared_ptr< ::hospitalbot::Motor > MotorPtr;
typedef boost::shared_ptr< ::hospitalbot::Motor const> MotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hospitalbot::Motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hospitalbot::Motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hospitalbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hospitalbot': ['/home/darkboy/catkin_ws/src/hospitalbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::Motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::Motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hospitalbot::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2787926effe38eff5cbbbb8aa59dbcd";
  }

  static const char* value(const ::hospitalbot::Motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2787926effe38efULL;
  static const uint64_t static_value2 = 0xf5cbbbb8aa59dbcdULL;
};

template<class ContainerAllocator>
struct DataType< ::hospitalbot::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hospitalbot/Motor";
  }

  static const char* value(const ::hospitalbot::Motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hospitalbot::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_velocity\n\
float64 right_velocity\n\
uint64 time\n\
";
  }

  static const char* value(const ::hospitalbot::Motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hospitalbot::Motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_velocity);
      stream.next(m.right_velocity);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hospitalbot::Motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hospitalbot::Motor_<ContainerAllocator>& v)
  {
    s << indent << "left_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.left_velocity);
    s << indent << "right_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.right_velocity);
    s << indent << "time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOSPITALBOT_MESSAGE_MOTOR_H
