// Generated by gencpp from file hospitalbot/RobotState.msg
// DO NOT EDIT!


#ifndef HOSPITALBOT_MESSAGE_ROBOTSTATE_H
#define HOSPITALBOT_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hospitalbot
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : id(0)
    , activity(0)
    , message()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : id(0)
    , activity(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _activity_type;
  _activity_type activity;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;




  typedef boost::shared_ptr< ::hospitalbot::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hospitalbot::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::hospitalbot::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::hospitalbot::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::hospitalbot::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hospitalbot::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hospitalbot::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hospitalbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hospitalbot': ['/home/darkboy/catkin_ws/src/hospitalbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hospitalbot::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hospitalbot::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hospitalbot::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hospitalbot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b870aa9b4f60acf1f190ddb8fbd201";
  }

  static const char* value(const ::hospitalbot::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b870aa9b4f60acULL;
  static const uint64_t static_value2 = 0xf1f190ddb8fbd201ULL;
};

template<class ContainerAllocator>
struct DataType< ::hospitalbot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hospitalbot/RobotState";
  }

  static const char* value(const ::hospitalbot::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hospitalbot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8 activity\n\
string message\n\
";
  }

  static const char* value(const ::hospitalbot::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hospitalbot::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.activity);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hospitalbot::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hospitalbot::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "activity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activity);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOSPITALBOT_MESSAGE_ROBOTSTATE_H
