# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hospitalbot/Battery.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Battery(genpy.Message):
  _md5sum = "e743845835d4deeeefdd5b5abae7a1f4"
  _type = "hospitalbot/Battery"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 voltage
uint8 maximum_level
uint8 current_level
bool charging"""
  __slots__ = ['voltage','maximum_level','current_level','charging']
  _slot_types = ['float32','uint8','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       voltage,maximum_level,current_level,charging

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Battery, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.voltage is None:
        self.voltage = 0.
      if self.maximum_level is None:
        self.maximum_level = 0
      if self.current_level is None:
        self.current_level = 0
      if self.charging is None:
        self.charging = False
    else:
      self.voltage = 0.
      self.maximum_level = 0
      self.current_level = 0
      self.charging = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f3B().pack(_x.voltage, _x.maximum_level, _x.current_level, _x.charging))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.voltage, _x.maximum_level, _x.current_level, _x.charging,) = _get_struct_f3B().unpack(str[start:end])
      self.charging = bool(self.charging)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f3B().pack(_x.voltage, _x.maximum_level, _x.current_level, _x.charging))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.voltage, _x.maximum_level, _x.current_level, _x.charging,) = _get_struct_f3B().unpack(str[start:end])
      self.charging = bool(self.charging)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f3B = None
def _get_struct_f3B():
    global _struct_f3B
    if _struct_f3B is None:
        _struct_f3B = struct.Struct("<f3B")
    return _struct_f3B
